######### CONFIGURACIÓN BASE###############################################
##      Acá se almacenan datos de configuración base.                    ##
## Es recomendable no hacer los cambios desde este archivo directamente  ##
## si no por medio del editor de CMS.                                    ##
##                                                                       ##
###########################################################################


#NOMBRE DE LA MARCA
name: Pamela Bustos

#TITULO PRINCIPAL QUE FIGURA EN LAS PESTAÑAS
title: Pamela Bustos | Vestidos diseñados para que solo pienses en bailar

#CORREO ELECTRONICO DEL SITIO WEB
email: ejemplo@gmail.com

#DESCRIPCION QUE FIGURA EN LA BUSQUEDA DE GOOGLE
description: Indumentaria femenina milonguera. Diseños personalizados y algo más. Vestidos diseñados para que solo pienses en bailar

#Social
#twitter_username: 
#github_username:  

index:
  es: index.html
  en: index_en.html
portfolio:
  es: portfolio.html
  en: portfolio_en.html
blog:
  es: blog.html
  en: blog_en.html

############################################################  

#defaults:                                                  #
#  - scope:                                                 #
#      path: ""                                             #
#      type: "post"                                         #
#    values:                                                #
#      layout: "blog"                                       #

#########NO MODIFICAR#######################################
#DIRECCION BASE                                            #
baseurl: "/" # the subpath of your site, e.g. /blog        #
#                                                          #
#DOMINIO DEL SITIO WEB                                     #
url: "https://pamelabustos.github.io"                      #
#                                                          # 
# Build settings                                           #
theme: minima                                              #
#                                                          #
#Material Design Bootstrap                                 # 
mdb: false                                                  #
#                                                          #
plugins:                                                   #
  - jekyll-feed                                            #
  - jekyll-sitemap                                         #
  - jekyll-seo-tag                                         #
#                                                          #
#Lets to publish future posts dates                        #
future: true                                               #  
#                                                          #
#Collections                                               #
collections:                                               #                                                         #
  galeria:                                                 #
    output: false                                          #
  albums:
    output: true
#                                                          #  
#  testimonios:                                             #
#    output: false                                          #
##################                                         #
#defaults:                                                  #
#  - scope:                                                 #
#      path: ""                                             #
#      type: "eventos"                                      #
#    values:                                                #
#      layout: "eventos"                                    #
#  - scope:                                                 #
#      path: ""                                             #
#      type: "clases"                                       #
#    values:                                                #
#      layout: "clases"                                     #
############################################################

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


